### ISSUE TITLE
LED's to flash while assistant talks

### ISSUE THREAD

**Issue by aceycv8** [respeaker/mic_hat#2] opened 2017-09-24 01:57 UTC
Hi,

i've got Assistant setup and mostly working the way i want it to be working however i can't get the lights to flash while assistant is talking - once it finishes thinking the lights dont flash any more.

i see this code in the google_assistant.py file

```
if event.type == EventType.ON_RESPONDING_STARTED:
        pixels.speak()
```

and when i look at 

pixels.py i see:

```
def _speak(self):
        colors = self.colors

        self.next.clear()
        while not self.next.is_set():
            for i in range(5, 25):
                colors = [(v * i / 24) for v in colors]
                self.write(colors)
                time.sleep(0.01)

            time.sleep(0.3)

            for i in range(24, 4, -1):
                colors = [(v * i / 24) for v in colors]
                self.write(colors)
                time.sleep(0.01)

            time.sleep(0.3)

        self._off()
```

so i dont see why it doesn't work
can you assist?

thank you

**Comment by xiongyihui** [comment] 2017-09-24 13:41
Have you enabled SPI？

**Comment by aceycv8** [comment] 2017-09-24 13:44
yes - i get lights when i say ok google - they light up and then once ive said what i want the lights flash like it's thinking but then when assistant speaks nothing happens

**Comment by jerryyip** [comment] 2017-09-24 16:02
@aceycv8 
please modify the code to:
```
            for i in range(5, 25):
                self.write([(v * i / 12) for v in colors])
``` 
When `colors = [(v * i / 24) for v in colors]`, `colors` will be zeroed at first so the LEDs can't light up.
We will fix this problem ASAP. Thanks for your feedback.

**Comment by aceycv8** [comment] 2017-09-24 22:06
Thanks Jerryyip

that works now!

**Comment by jerryyip** [comment] 2017-09-25 00:09
Ok, as the problem is solved, I will close this issue.

**Closed as completed by jerryyip** 2017-09-25 00:09 UTC
